apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creditsea-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-size: "4096" # Used for some API as per Mr. Ankur Gour
    cert-manager.io/private-key-rotation-policy: "Always"
    service.beta.kubernetes.io/aws-load-balancer-name: "creditsea-api-lb"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - api.creditsea.com
    secretName: creditsea-tls
  rules:
  - host: api.creditsea.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: creditsea-app-service
            port:
              number: 80
