apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditsea-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: creditsea=533267250939.dkr.ecr.ap-south-1.amazonaws.com/creditsea-app
    argocd-image-updater.argoproj.io/creditsea.update-strategy: latest
  labels:
    app: creditsea-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creditsea-app
  template:
    metadata:
      labels:
        app: creditsea-app
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: creditsea-app
          image: 533267250939.dkr.ecr.ap-south-1.amazonaws.com/creditsea-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 500m
          envFrom:
            - secretRef:
                name: creditsea-config-secret
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: creditsea-app-config
