apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditsea-app
  labels:
    app: creditsea-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::533267250939:role/ArgocdImageUpdaterRole
    keel.sh/policy: minor 
    keel.sh/trigger: poll
spec:
  revisionHistoryLimit: 0 # delete old replicaSet after reaching "complete state"
  replicas: 2
  selector:
    matchLabels:
      app: creditsea-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: creditsea-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - m5.large
                - c5.large
                - r5.large
      tolerations:
        - key: CriticalAddonsOnly # HACK: this ensures it runs inside karpenter 
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: creditsea-app
          image: 533267250939.dkr.ecr.ap-south-1.amazonaws.com/creditsea-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 3Gi
              cpu: 800m
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: creditsea-config-secret
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: creditsea-app-config
