apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: creditsea-config-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: creditsea-config-secret
    creationPolicy: Owner
  data:
  - secretKey: config.json
    remoteRef:
      key: creditsea-config
