apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - cluster-issuer.yaml
  - configmap.yaml
  - deployment.yaml
  - externalSecret.yaml
  - secret-store.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: creditsea
  app.kubernetes.io/part-of: creditsea-backend

namespace: default
