apiVersion: v1
kind: Service
metadata:
  name: creditsea-app-service
  labels:
    app: creditsea-app
spec:
  type: ClusterIP  # Change from LoadBalancer to ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: creditsea-app
