apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd  # Make sure this is the namespace where ArgoCD is running
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.4
    helm:
      values: |         
        installCRDs: true  # Make sure CRDs are installed
        replicaCount: 1
        fullnameOverride: "external-secrets"
        serviceAccount:
          create: true
          name: external-secrets-operator
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::533267250939:role/external-secrets-role
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
